config/routes.rb
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Main App
  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations", sessions: 'sessions', :passwords => "passwords"}
  devise_scope :user do
      post "users/login_or_sign_up_phone" => "sessions#login_or_sign_up_phone", as: :login_or_sign_up_phone
      match "verify_phone" => "sessions#verify_phone", as: :verify_phone, via: [:get, :post]
  end
  resources :users, only: [ :show, :edit, :update] do
    member do
      get 'unsubscribe'
    end
  end

  #Yext
  namespace :powerlistings do
    get 'categories' => 'categories#index', defaults: {format: 'json'}
    get 'search' => 'listings#index', defaults: {format: 'json'}
    get 'details' => 'listings#show', defaults: {format: 'json'}
    post 'order' => 'listings#upsert', defaults: {format: 'json'}
    put '/:id' => 'listings#update', defaults: {format: 'json'}
    delete '/:id' => 'listings#cancel', defaults: {format: 'json'}
    post 'suppress/:id' => 'listings#suppress', defaults: {format: 'json'}
    get 'reviews' => 'listings#reviews', defaults: {format: 'json'}
  end
  resources :patient_stories do
    member do
      get :download
    end
  end

  get 'sitemap', to: 'sitemaps#index', defaults: {format: 'html'}

  post "interested_provider_contact" => "users#provider_email_request", as: :interested_provider_contact
  post "create_subscription_only_user" => "users#create_subscription_only"
  get "create_claim_request", to: "claim_requests#create", as: :create_claim_request
  get "create_doctor_claim_request", to: "doctor_claim_requests#create", as: :create_doctor_claim_request
  get 'contributors' => 'static_pages#editorial_board', as: :editorial_board
  get "privacy-policy" => "static_pages#privacy_policy"
  get "terms" => "static_pages#terms"
  get "copyright" => "static_pages#copyright"
  get "faqs" => "static_pages#faqs"
  get "press" => "static_pages#press"
  get "careers" => "static_pages#careers"
  get "about" => "static_pages#about"
  get "claims/(:id)" => "static_pages#manage", as: :manage
  get "users/(:id)" => "static_pages#users_info", as: :users_info
  get '/home/(:set_locale)' => "home#index"
  get "india" => "home#india"
  get "calculators" => "static_pages#calculators"
  get "bmi_calculator" => "static_pages#bmi_calculator"
  get "waist_hip_calculator" => "static_pages#waist_hip_calculator"
  get "bmr_calculator" => "static_pages#bmr_calculator"
  get "calorie_calculator" => "static_pages#calorie_calculator"
  post "email_my_calculator_results" => "users#mail_calculator_results"

  # Health Guides
  get "health-guide" => "health_guides#index"
  get "health-guides" => "static_pages#health_guide"
  scope 'health-guide', as: :health_guide do
    get ":co" => "health_guides#show", as: :co
  end

  # Faq / Forum
  get "/forum" => "faqs#index"
  resources :faqs, only: [ :create, :update ] do
    resources :faq_answers, only: :create
  end

  get "/blog/tag/:tag" => "blogs#index", as: :blogs_tag
  resources :blogs, path: "blog", only: [ :index, :show] do
    member do
      patch 'share_blog/:social_platform', action: 'share_blog', defaults: {format: 'json'}
    end
  end
  resources :contacts, only: [:new, :create]
  resources :advertising_requests, only: [:new, :create]

  get "locations/compare" => "compare#index", as: :search_hospital_compare
  get "locations/compare" => "compare#index", as: :search_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_travel_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_healthcare_facilities_compare
  get "doctors/compare" => "doctor_compare#index", as: :search_doctor_compare

  # Search Prep
  get "home-prep-hospitals" => "home#prep_hospitals", as: :prep_hospital_search
  get "home-prep-health-insurance" => "home#prep_health_insurance", as: :prep_health_insurance_search

  post "agree_to_gdpr" => "home#agree_to_gdpr"
  # Search
  get "hospitals" => "searches#show", as: :search_hospitals
  get "doctors" => "doctor_search#show", as: :search_doctors
  get "typeahead" => "doctor_search#typeahead_search", as: :search_typeahead

  get "practices" => "practice#show", as: :search_practices
  get "health-insurance/(:set_locale)" => "health_insurance#show", as: :search_health_insurances
  get "travel-health-insurance/(:set_locale)" => "travel_health_insurance#show", as: :search_travel_health_insurances
  get "healthcare-facilities/(:set_locale)" => "healthcare_facilities#show", as: :search_healthcare_facilities

  get "best-hospital-ratings/:set_locale/(:state)/(:city)" => "searches#best_hospitals", as: :search_best_hospitals
  get "best_hospitals/:set_locale/(:state)/(:city)" => "searches#best_hospitals"
  get '/best-hospital-ratings/:country/:state/:city/:id/reviews', controller: :locations, action: :show
  get '/best-hospital-ratings/:country/:state/:city/:id', controller: :locations, action: :show
  get '/practices/:top_speciality/:country/:state/:city/:id', controller: :locations, action: :practice

  get '/health-insurance/:country/:id', controller: :locations, action: :health_insurance
  get '/travel-health-insurance/:country/:id', controller: :locations, action: :travel_health_insurance

  get "best_doctors/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors"
  get "practices/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_practices

  get "best-doctor-ratings/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_doctors
  get '/best-doctor-ratings/:top_speciality/:country/:state/:city/:id', controller: :doctors, action: :show

  post "/blog/image-upload" => 'admin/blogs#image_upload'

  resources :ratings, only: [] do
    resources :comments
  end

  resources :doctor_reviews, only: [] do
    resources :comments
  end
  
  resources :practice_reviews, only: [] do
    resources :comments
  end

  resources :questions, :only => [] do
    resources :answers, only: [:new, :create]
  end

#trailing out health rating
  resources :hs


     get "patient-experience-awards" => "awards#index", as: :awards
     match 'excellent-patient-experience-awards-doctors' => 'awards#gold_doctors', as: :gold_doctors_awards, via: [:get, :post]
     match 'excellent-patient-experience-awards-hospitals' => 'awards#gold_hospitals', as: :gold_hospitals_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-doctors' => 'awards#diamond_doctors', as: :diamond_doctors_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-hospitals' => 'awards#diamond_hospitals', as: :diamond_hospitals_awards, via: [:get, :post]

  # API
  namespace :api do
    get "votes/:voteable_type/:voteable_id/:status" => "votes#create"
    resources :locations, only: :index
    # resources :doctor_organizations, only: :index
    resources :doctors, only: :index
    resources :reset_passwords, only: [:index, :create]
    resources :register_user, defaults: {format: 'json'} do
      collection do
       post 'create_user'
       post 'login'
       delete 'logout'
       get "/doctor_show" => "/api/doctors#doctor_show"
       get "/hospital_show" => "/api/doctors#hospital_show"
       get "/doctor_review" => "/api/doctors#doctor_review"
       get "/hospital_review" => "/api/doctors#hospital_review"
       post "/update_profile" => "/api/register_user#update_profile"
       get "/healthinsurance_show" => "/api/doctors#healthinsurance_show"
       get "/healthinsurance_review" => "/api/doctors#healthinsurance_review"
       post "/create_review" => "/api/doctors#create_review"
       post "/create_hospital_review" => "/api/doctors#create_hospital_review"
       post "/create_insurance_review" => "/api/doctors#create_insurance_review"
       get "/mailchimp" => "/api/mailchimp#mailchimp"
       post "/create_appointment" => "/api/appointment#create_appointment"
       get "/appointment_show" => "/api/appointment#appointment_show"
       get "/user_point_review" => "/api/register_user#user_point_review"
       get "/search_doctor" => "/api/search#search_doctor"
       get "/search_hospital" => "/api/locations#search_hospital"
       get "/search_health_insurance" => "/api/health_insurance#search_health_insurance"
      end
    end
  end

  # manager
  namespace :manage do
    resources :locations
    resources :doctors do
      get "show1"
      get "reply_review/:rating_id" => "doctors#reply_review"
      post "save_review"
    end
  end

  # Admin
  namespace :admin do
    root to: "dashboard#index"
    resources :advertisements do
      member do
        match 'resource_mapping' => "advertisements#resource_mapping", via: [:get, :patch]
      end
    end
    resources :board_certifications
    resources :doctor_hospitals do
      collection do
        post "import"
      end
    end
    resources :languages
    resources :medical_students
    resources :events
    resources :event_members
    resources :editorial_members
    resources :appointments
    resources :location_types
    resources :locations do
      member do
        post 'analytics_report' => 'locations#analytics_report'
      end
    end
    resources :conditions
    resources :doctors do
      member do
        post 'analytics_report' => 'doctors#analytics_report'
      end
    end
    resources :users
    resources :claim_requests
    resources :questions
    resources :ratings
    resources :doctor_reviews
    resources :practice_reviews
    resources :speciality_merges
    resources :doctor_reports, only: :index
    get "practices" => "doctors#practices"
    get "doctor_reports/doctor_uploads" => "doctor_reports#doctor_uploads"
    resources :practice_specialities do 
      member do
        get 'faqs' => 'practice_specialities#faqs'
      end
    end
    resources :practice_specialities_faqs
    resources :procedures
    resources :blogs

app/models/location_type.rb
class LocationType < ApplicationRecord
  has_many :locations

  def hospital?
    name == "Hospital"
  end

  def insurance_company?
    name == "Health Insurance"
  end

  def travel_insurance?
    name == "Travel Health Insurance"
  end

  def practice?
    name == 'Practice'
  end

  def healthcare_facilities?
    !["Hospital", "Health Insurance", "Travel Health Insurance", "Practice"].include?(name)
  end

  def self.practice_obj
    where(name: 'Practice')&.last
  end

end

app/controllers/admin/import/locations_controller.rb
class Admin::Import::LocationsController < Admin::BaseController
  def create
    ImportJob.perform_async(params)
    redirect_to admin_locations_path, notice: "Locations Importing"
  end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController <  Admin::ResourceController
  def index
    klass
    if search_params.present?
      @search = Search::AdminSearch.new(search_params)
    else
      @search = Search::AdminSearch.new
     # @search.co = default_locale
    end
    @resources = @search.results.reorder(:hwaid).page(page[:page].to_i).per(100)
  end

  def new
    if params[:location_type_id].present?
      @resource = Location.new(location_type_id: params[:location_type_id])
    end
  end

  def analytics_report
    @resource = Location.where(slug: params[:id]).first
    chart_url = params[:location][:analytic_chart]
    chart_url = chart_url.gsub("data:image/png;base64,", '')
    chart_href = "#{Rails.root}/tmp/chart_#{@resource.class.name.downcase}_#{@resource.id}.png"
    File.open(chart_href, 'wb') do |f|
      f.write(Base64.decode64(chart_url))
    end
    params[:location][:analytic_chart_href] = chart_href
    AnalyticsMailer.analytics_report(@resource, params[:location]).deliver_now
    flash[:notice] = 'Mail sent successfully.'
    redirect_to :back
  end

  private

  def search_params
    if params[:search_admin_search].present?
      params.require(:search_admin_search).permit(:hwaid, :location_type_id, :co, :sub_type, :without_geolocation, :lat, :lng, :near, :city, :state, :name, :within, :co, :stars => [])
    end
  end

  def page
    params.permit(:page)
  end

  def update_path
    [:admin, @resource]
  end
end

app/helpers/location_helper.rb
module LocationHelper

  def location_path(loc, options={})
    location_url(loc, options.merge(:only_path => true))
  end

  def location_url(loc, options={})
    if loc.hospital?
      url_for(options.merge(controller: '/locations', action: :show,
        country: loc.country_slug.presence || 'NA', 
        state: loc.state_slug.presence || 'NA', 
        city: loc.city_slug.presence || 'NA', 
        id: loc.slug  || loc.id))
    elsif ['Location', 'LocationDecorator'].include?(loc.class.to_s) && loc.location_type.name == 'Practice'
      url_for(options.merge(controller: '/locations', action: :practice,
        top_speciality: loc.top_speciality.presence || 'NA' , 
        country: loc.country_slug.presence || 'NA', 
        state: loc.state_slug.presence || 'NA', 
        city: loc.city_slug.presence || 'NA', 
        id: loc.slug || loc.id))
    elsif loc.insurance_company? 
      url_for(options.merge(controller: '/locations', action: :health_insurance,
        country: loc.country_slug.presence || 'NA', 
        id: loc.slug || loc.id))
    elsif loc.travel_insurance?
      url_for(options.merge(controller: '/locations', action: :travel_health_insurance,
        country: loc.country_slug.presence || 'NA', 
        id: loc.slug || loc.id))
    else
      url_for(options.merge(controller: '/locations', action: :show, id: loc.slug || loc.id))
    end
  end

  def website_link(link)
    return "" if link.blank?
    link_to link, sanitize_link(link), target: "_blank"
  end

  def stars(rating)
    content_tag(:span, nil, data: {stars: rating})
  end

  def number(num)
    "%g" % num
  end

  def sanitize_link(link)
    if link.to_s.include?("http")
      link
    else
      "//#{link}"
    end
  end

  def location_image(location)
    if location.image.present?
      image_location(location)
    else
      no_image_location(location)
    end
  end

  def image_location(location)
    alt = location.photo_alt
    content_tag(:div, nil, class: :circle_image, style: "background-image: url(#{location.image})", title: alt)
  end

  def no_image_location(location)
    alt = location.photo_alt
    content_tag(:div, location.initials, class: :circle_image, title: alt)
  end

  def recommend_tag(bool)
    case bool
    when "Yes"
      content_tag(:span, "Yes", class: "label success")
    when "Maybe"
      content_tag(:span, "Maybe", class: "label secondary")
    else
      content_tag(:span, "No", class: "label warning")
    end
  end

  def back_to_search_button(location)
    if location.doctor?
      path = search_doctors_path
    elsif location.insurance_company?
      path = search_health_insurances_by_country_path
    elsif location.travel_insurance?
      path = search_travel_health_insurances_by_country_path
    elsif location.practice?
      path = search_practices_path
    else
      path = search_hospitals_path
    end
    link_to path,  class: 'back-to-search-button' do
      ("<i class='glyphicon glyphicon-arrow-left'></i> " +
       t(:back_to_search)).html_safe
    end
  end

  def favorites_button(user, location)
    icon_class = 'glyphicon-heart-empty'
    location_type = location.doctor? ? 'doctor' : 'location'
    favorite_text = "Add to Favorites"
    path_for_favorite = "/#{location_type}s/#{location.id}/save_favorite?type=#{location_type}&slug=#{location.slug}"
    if location.favorites.where(user_id: user.id).present?
      icon_class = 'glyphicon-heart'
      path_for_favorite = "/#{location_type}s/#{location.id}/remove_favorite?type=#{location_type}&slug=#{location.slug}"
      favorite_text = "In Favorites"
    end
    link_to path_for_favorite, method: :post do
      ("<h4><i class='glyphicon #{icon_class} favorite-link'></i> #{favorite_text}</h4>").html_safe
    end
  end

  def rating_url(location)
    location.practice? ? new_location_practice_review_url(location) : url_for([:new, location, :rating])
  end

end

app/views/admin/locations/_business_hour_fields.html.slim
.nested-fields
  .row
    .small-2.large-3.columns
      = f.input :day, collection: BusinessHour::SELECT_VALUES
    .small-2.large-3.columns
      = f.input :start_time, collection: BusinessHour.create_time, selected: f.object.start_time
    .small-2.large-3.columns
      = f.input :end_time, collection: BusinessHour.create_time, selected: f.object.end_time
    .small-2.large-2.columns.align-middle
      = f.input :closed
    .small-2.large-1.columns.align-middle
      = link_to_remove_association "Remove", f
hr

app/views/admin/locations/_business_hours_section.html.slim
p
  strong Business Hours - Set Both Start and End Time as 0:00AM If Open 24 Hours
  br
  strong Marking Day As Closed Will Override any time set
  = f.simple_fields_for :business_hours, f.object.business_hours.order("day ASC, start_time ASC") do |al|
    = render 'business_hour_fields', f: al
  .links
    = link_to_add_association 'Add Day', f, :business_hours

app/views/admin/locations/_form.html.slim
.row
  .large-12.columns
    =simple_form_for [:admin, @resource] do |f|
      .row
        .small-2.large-4.columns
          =f.input :name
        .small-2.large-2.columns
          =f.input :hwaid
        .small-2.large-2.columns.align-middle
          =f.input :is_claimed
        .small-2.large-4.columns
          = f.input :featured_or_sponsored, as: :radio_buttons, collection: FEATURED_OR_SPONSORED, label: false 

      .row
        -unless f.object.practice?
          .small-2.large-4.columns
            = f.association :location_type
        .small-2.large-4.columns
          = f.input :sub_type 
        .small-2.large-4.columns
          - if !@resource.new_record?
            label Slug
            = @resource.slug
      
      .row  
        .small-2.large-12.columns
          =f.input :description
      .row
        .small-2.large-6.columns
          =f.input :address
        .small-2.large-6.columns
          =f.input :address2
      .row
        .small-2.large-4.columns
          =f.input :city
        .small-2.large-4.columns
          =f.input :state
        .small-2.large-4.columns
          =f.input :zip
      .row
        .small-2.large-12.columns
          =f.input :country, as: :select, collection: country_collection
      .row
        .small-2.large-4.columns
          =f.input :website, as: :url
        .small-2.large-4.columns
          =f.input :phone
        .small-2.large-4.columns
          =f.input :email
      .row
        .small-2.large-4.columns.align-middle
          =f.input :simple_geocode, label: 'Simple Geocode? (Geocode by city, state, zip, country)'
        .small-2.large-4.columns
          =f.input :latitude, disabled: true
        .small-2.large-4.columns
          =f.input :longitude, disabled: true
      .row
        .small-2.large-8.columns
          = f.input :photo, as: :file, label: 'Upload Photo'
          = f.hidden_field :photo_cache
          - if @resource.photo?
            - alt = @resource.photo_alt
            = image_tag(@resource.photo.thumb.url, alt: alt)
            br
            label
              | Remove Photo
              = f.check_box :remove_photo
        .small-2.large-4.columns
          = f.input :photo_alt, label: 'Photo ALT text'
        - if f.object.practice?
          table
            / Split specialities into groups of three to render checkbox rows as rows of a table
            - PracticeSpeciality.where(common_speciality: true).sort_by{|ps| ps.name}.in_groups_of(3).each do |common|
              tr
                =f.association :practice_specialities, as: :check_boxes, collection: common.reject { |i| i.nil?}, label: false, item_wrapper_tag: :td, boolean_style: :inline, item_wrapper_class: "speciality"
          label Other Specialities
          table
            / Split specialities into groups of three to render checkbox rows as rows of a table
            - PracticeSpeciality.where(common_speciality: false).sort_by{|ps| ps.name}.in_groups_of(3).each do |other|
              tr
                =f.association :practice_specialities, as: :check_boxes, collection: other.reject { |i| i.nil?}, label: false, item_wrapper_tag: :td, boolean_style: :inline, item_wrapper_class: "speciality"
      - if @resource.practice? || @resource.hospital?
        hr
        = render 'business_hours_section', f: f
      .row
        .small-2.large-6.columns
          =f.input :placeid, label: 'Place'
        .small-2.large-6.columns
          =f.input :place_photo
      .row
        .small-2.large-12.columns
          =f.button :button

app/views/admin/locations/_list.html.slim
tr
  td
    - if list.image.present?
      - alt = list.photo_alt
      = image_tag(list.image, width: 75, alt: alt)
  td=list.hwaid
  td=list&.location_type&.name
  td
    =link_to list.name, admin_location_path(list)
    br
    small=list.full_street_address
  td
    =list.city
    - if list.state.present?
      | , 
      =list.state
    |  
    span.label.secondary=list.country
  td=list.lat_lng

  td=link_to "Edit", [:edit, :admin, list], class: 'button tiny'

app/views/admin/locations/index.html.slim
h1=@resource_name

.button-group
  =link_to "Add", [:new, :admin, @resource_slug.singularize ], class: "button"
  =link_to "Import", [:new, :admin, :import, @resource_slug.singularize ], class: "button"
  =link_to "Types", [:admin, :location_types], class: "button"

.well
  = simple_form_for @search, method: :get, url: admin_locations_path, data: {search_form: "ajax"} do |f|
    .row
      .columns.medium-4
        =f.input :name, placeholder: '', label: 'Name'
      .columns.medium-3
        =f.input :state, placeholder: "State", label: "Near"
      .columns.medium-3
        =f.input :co, as: :select, collection: @search.countries_select_code, label: 'Country', prompt: "Any Country"
      .columns.medium-2.align-middle
        =f.input :without_geolocation, as: :boolean
    .row
      .columns.medium-4
        =f.input :location_type_id, as: :select, collection: LocationType.all.order(:name)
      .columns.medium-3
        =f.input :hwaid, label: "HWA ID"
      .columns.medium-4.align-middle
        =f.button :button, "Search", value: 'Search'


- if @resources.present?
  br
  .text-center
    = paginate(@resources)

table
  thead
    tr
      th
      th HWAId
      th Type
      th Name
      th Location
      th Lat/Lng?
      th
  tbody
    = render partial: "list", collection: @resources

- if @resources.present?
  .text-center
    = paginate(@resources)

app/views/admin/locations/new.html.slim
h1.text-center
  - if @resource.practice?
    | New Practice
  - else
    | New Location
.well
  =render "form"

app/views/admin/locations/show.html.slim
h1=@resource.name
h3=@resource.hwaid
.button-group
  =link_to "Visit public page", location_path(@resource), class: 'button'
  =link_to "Edit", edit_admin_location_path(@resource), class: 'button'
  =link_to "Delete", admin_location_path(@resource), method: :delete, data: {confirm: "Are you sure? This will delete all associated reviews, questions, answers, etc with this location"}, class: 'button alert'
.row
  .large-7.columns
    table
      = render partial: 'manage/locations/location_info', locals: {location: @resource}

  .columns.large-5
    = render partial: 'manage/locations/analytics_chart', locals: {location: @resource}

    hr

    h4 Mail Analytics:
    =simple_form_for @resource, method: :post, url: analytics_report_admin_location_path(@resource.slug), html: {multipart: true}  do |f|
      .row
        .columns.medium-12
          #error
      .row
        .columns.medium-9
          = f.input :email, type: "email", required: true
          = f.input :analytic_chart, as: :hidden
        .columns.medium-3.mt-20
          = f.button :button, "Send Mail", onclick: "javascript: return allow_for_submission();"

    hr
    h3 Moderators:
    ul
      - User.with_role(:moderator, @resource).each do |user|
        li=link_to user.email, edit_admin_user_path(user)

    - if @resource.claim_requests.present?
      hr
      h3 Claim Requests:
      ul
        - @resource.claim_requests.each do |claim_request|
          li=link_to claim_request.position, edit_admin_claim_request_path(claim_request)

.row
  .columns
    hr
    h3 Choose another photo
    p Click on the photo to make it current.
    #place-photos[data-id="#{@resource.slug}"]
    br.clear
    br
    hr
    - content_for :extra_js do
      javascript:
        initShowPlacePhotos(#{@resource.latitude},#{@resource.longitude}, "#{@resource.name}", "#{@resource.placeid}")
        
= render partial: 'manage/widget', locals: {obj: @resource, type: @resource.location_type.name.downcase.gsub(" ", "_")}