config/routes.rb
Rails.application.routes.draw do

  resources :hdetails
  resources :hsdetails
  apipie
  mount ActionCable.server => '/healthsoul_action_cable'

  resources :advertisements, only: [:show]
  resources :events, only: [:show, :index] do
    resources :event_members, only: [:new, :create, :index]
  end
  resources :medical_students, only: [:new, :create, :index, :show] do
    resources :claim_requests, only: [:new, :create], controller: "medical_student_claim_requests"
  end

  get "practice_specialities/:id/:country/:type" => "practice_specialities#index", as: :speciality_faqs
  get 'recommendations/:source_type' => 'recommendations#new', as: :new_recommendation
  resources :recommendations, only: [:create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # Main App
  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks', :registrations => "registrations", sessions: 'sessions', :passwords => "passwords"}
  devise_scope :user do
      post "users/login_or_sign_up_phone" => "sessions#login_or_sign_up_phone", as: :login_or_sign_up_phone
      match "verify_phone" => "sessions#verify_phone", as: :verify_phone, via: [:get, :post]
  end
  resources :users, only: [ :show, :edit, :update] do
    member do
      get 'unsubscribe'
    end
  end

  #Yext
  namespace :powerlistings do
    get 'categories' => 'categories#index', defaults: {format: 'json'}
    get 'search' => 'listings#index', defaults: {format: 'json'}
    get 'details' => 'listings#show', defaults: {format: 'json'}
    post 'order' => 'listings#upsert', defaults: {format: 'json'}
    put '/:id' => 'listings#update', defaults: {format: 'json'}
    delete '/:id' => 'listings#cancel', defaults: {format: 'json'}
    post 'suppress/:id' => 'listings#suppress', defaults: {format: 'json'}
    get 'reviews' => 'listings#reviews', defaults: {format: 'json'}
  end
  resources :patient_stories do
    member do
      get :download
    end
  end

  get 'sitemap', to: 'sitemaps#index', defaults: {format: 'html'}

  post "interested_provider_contact" => "users#provider_email_request", as: :interested_provider_contact
  post "create_subscription_only_user" => "users#create_subscription_only"
  get "create_claim_request", to: "claim_requests#create", as: :create_claim_request
  get "create_doctor_claim_request", to: "doctor_claim_requests#create", as: :create_doctor_claim_request
  get 'contributors' => 'static_pages#editorial_board', as: :editorial_board
  get "privacy-policy" => "static_pages#privacy_policy"
  get "terms" => "static_pages#terms"
  get "copyright" => "static_pages#copyright"
  get "faqs" => "static_pages#faqs"
  get "press" => "static_pages#press"
  get "careers" => "static_pages#careers"
  get "about" => "static_pages#about"
  get "claims/(:id)" => "static_pages#manage", as: :manage
  get "users/(:id)" => "static_pages#users_info", as: :users_info
  get '/home/(:set_locale)' => "home#index"
  get "india" => "home#india"
  get "calculators" => "static_pages#calculators"
  get "bmi_calculator" => "static_pages#bmi_calculator"
  get "waist_hip_calculator" => "static_pages#waist_hip_calculator"
  get "bmr_calculator" => "static_pages#bmr_calculator"
  get "calorie_calculator" => "static_pages#calorie_calculator"
  post "email_my_calculator_results" => "users#mail_calculator_results"

  # Health Guides
  get "health-guide" => "health_guides#index"
  get "health-guides" => "static_pages#health_guide"
  scope 'health-guide', as: :health_guide do
    get ":co" => "health_guides#show", as: :co
  end

  # Faq / Forum
  get "/forum" => "faqs#index"
  resources :faqs, only: [ :create, :update ] do
    resources :faq_answers, only: :create
  end

  get "/blog/tag/:tag" => "blogs#index", as: :blogs_tag
  resources :blogs, path: "blog", only: [ :index, :show] do
    member do
      patch 'share_blog/:social_platform', action: 'share_blog', defaults: {format: 'json'}
    end
  end
  resources :contacts, only: [:new, :create]
  resources :advertising_requests, only: [:new, :create]

  get "locations/compare" => "compare#index", as: :search_hospital_compare
  get "locations/compare" => "compare#index", as: :search_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_travel_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_healthcare_facilities_compare
  get "doctors/compare" => "doctor_compare#index", as: :search_doctor_compare

  # Search Prep
  get "home-prep-hospitals" => "home#prep_hospitals", as: :prep_hospital_search
  get "home-prep-health-insurance" => "home#prep_health_insurance", as: :prep_health_insurance_search

  post "agree_to_gdpr" => "home#agree_to_gdpr"
  # Search
  get "hospitals" => "searches#show", as: :search_hospitals
  get "doctors" => "doctor_search#show", as: :search_doctors
  get "typeahead" => "doctor_search#typeahead_search", as: :search_typeahead

  get "practices" => "practice#show", as: :search_practices
  get "health-insurance/(:set_locale)" => "health_insurance#show", as: :search_health_insurances
  get "travel-health-insurance/(:set_locale)" => "travel_health_insurance#show", as: :search_travel_health_insurances
  get "healthcare-facilities/(:set_locale)" => "healthcare_facilities#show", as: :search_healthcare_facilities

  get "best-hospital-ratings/:set_locale/(:state)/(:city)" => "searches#best_hospitals", as: :search_best_hospitals
  get "best_hospitals/:set_locale/(:state)/(:city)" => "searches#best_hospitals"
  get '/best-hospital-ratings/:country/:state/:city/:id/reviews', controller: :locations, action: :show
  get '/best-hospital-ratings/:country/:state/:city/:id', controller: :locations, action: :show
  get '/practices/:top_speciality/:country/:state/:city/:id', controller: :locations, action: :practice

  get '/health-insurance/:country/:id', controller: :locations, action: :health_insurance
  get '/travel-health-insurance/:country/:id', controller: :locations, action: :travel_health_insurance

  get "best_doctors/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors"
  get "practices/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_practices

  get "best-doctor-ratings/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_doctors
  get '/best-doctor-ratings/:top_speciality/:country/:state/:city/:id', controller: :doctors, action: :show

  post "/blog/image-upload" => 'admin/blogs#image_upload'

  resources :ratings, only: [] do
    resources :comments
  end

  resources :doctor_reviews, only: [] do
    resources :comments
  end
  
  resources :practice_reviews, only: [] do
    resources :comments
  end

  resources :questions, :only => [] do
    resources :answers, only: [:new, :create]
  end

#trailing out health rating
  resources :hs


     get "patient-experience-awards" => "awards#index", as: :awards
     match 'excellent-patient-experience-awards-doctors' => 'awards#gold_doctors', as: :gold_doctors_awards, via: [:get, :post]
     match 'excellent-patient-experience-awards-hospitals' => 'awards#gold_hospitals', as: :gold_hospitals_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-doctors' => 'awards#diamond_doctors', as: :diamond_doctors_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-hospitals' => 'awards#diamond_hospitals', as: :diamond_hospitals_awards, via: [:get, :post]

  # API
  namespace :api do
    get "votes/:voteable_type/:voteable_id/:status" => "votes#create"
    resources :locations, only: :index
    # resources :doctor_organizations, only: :index
    resources :doctors, only: :index
    resources :reset_passwords, only: [:index, :create]
    resources :register_user, defaults: {format: 'json'} do
      collection do
       post 'create_user'
       post 'login'
       delete 'logout'
       get "/doctor_show" => "/api/doctors#doctor_show"
       get "/hospital_show" => "/api/doctors#hospital_show"
       get "/doctor_review" => "/api/doctors#doctor_review"
       get "/hospital_review" => "/api/doctors#hospital_review"
       post "/update_profile" => "/api/register_user#update_profile"
       get "/healthinsurance_show" => "/api/doctors#healthinsurance_show"
       get "/healthinsurance_review" => "/api/doctors#healthinsurance_review"
       post "/create_review" => "/api/doctors#create_review"
       post "/create_hospital_review" => "/api/doctors#create_hospital_review"
       post "/create_insurance_review" => "/api/doctors#create_insurance_review"
       get "/mailchimp" => "/api/mailchimp#mailchimp"
       post "/create_appointment" => "/api/appointment#create_appointment"
       get "/appointment_show" => "/api/appointment#appointment_show"
       get "/user_point_review" => "/api/register_user#user_point_review"
       get "/search_doctor" => "/api/search#search_doctor"
       get "/search_hospital" => "/api/locations#search_hospital"
       get "/search_health_insurance" => "/api/health_insurance#search_health_insurance"
      end
    end
  end

  # manager
  namespace :manage do
    resources :locations
    resources :doctors do
      get "show1"
      get "reply_review/:rating_id" => "doctors#reply_review"
      post "save_review"
    end
  end

  # Admin
  namespace :admin do
    root to: "dashboard#index"
    resources :advertisements do
      member do
        match 'resource_mapping' => "advertisements#resource_mapping", via: [:get, :patch]
      end
    end
    resources :board_certifications
    resources :doctor_hospitals do
      collection do
        post "import"
      end
    end
    resources :languages
    resources :medical_students
    resources :events
    resources :event_members
    resources :editorial_members
    resources :appointments
    resources :location_types
    resources :locations do
      member do
        post 'analytics_report' => 'locations#analytics_report'
      end
    end

app/models/claim_request.rb
class ClaimRequest < ApplicationRecord
  belongs_to :user
  # Author is the person who added this claim request - inshort it's login user who claim profile for self or behalf or other.
  belongs_to :author, class_name: "User", foreign_key: "created_by"
  accepts_nested_attributes_for :user,:update_only => true
  belongs_to :claimable, polymorphic: true, optional: true
  belongs_to :doctor, foreign_type: 'Doctor', foreign_key: 'claimable_id'
  belongs_to :location, foreign_type: 'Location', foreign_key: 'claimable_id'
  validates :user_id, uniqueness: { scope: [:claimable_id, :claimable_type], message: "You have already created a claim request" }, allow_nil: true
  validates :user_id, :description, :claimable_type, :claimable_id, :created_by, presence: true
  belongs_to :medical_student, foreign_type: 'MedicalStudent', foreign_key: 'claimable_id'

  scope :email_search, -> (query) { joins(:user).where("(REPLACE (lower(users.email), ' ', '' ) like ?)", "%#{query}%") }   

  def doctor
    return unless claimable_type == "Doctor"
    super
  end

   def location
     return unless claimable_type == "Location"
     super
   end

  def doctor?
    claimable_type == "Doctor"
  end

  def location?
    claimable_type == "Location"
  end

  def medical_student?
    claimable_type == "MedicalStudent"
  end

  def medical_student
    return unless claimable_type == "MedicalStudent"
    super
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/admin/claim_requests_controller.rb
class Admin::ClaimRequestsController < Admin::ResourceController
  def new
    @resource_name = self.controller_name.camelize
    @resource = ClaimRequest.new
    @resource.user = current_user
  end

  def create
    @resource_name = self.controller_name.camelize
    @resource = ClaimRequest.new(resource_params.except(:user))
    @resource.created_by = current_user.id
    if resource_params[:user].present?
      @resource.user.update_attributes(resource_params[:user].to_h)
    end
    if @resource.save
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def index
    @resources = ClaimRequest
    if request.xhr?
      claimable_model = params[:claimable]
      claimable_term = params[:claimable_term]
      user_name = params[:user_name]
      if claimable_model && claimable_term
        data = eval(claimable_model).where.not(name: nil).where(["name ilike ? or name ilike ?", "#{claimable_term}%",  "%#{claimable_term}%"]).order(name: :asc).page(params[:page]).per(5)
        render json: data.map{|v| {id: v.id, text: v.name} }
      elsif user_name
        data = User.where.not(email: nil).where(["username ilike ? or username ilike ? or email ilike ? or email ilike ?", "#{user_name}%",  "%#{user_name}%", "#{user_name}%",  "%#{user_name}%"]).order(email: :asc).page(params[:page]).per(5)
        render json: data.map{|v| {id: v.id, text: v.email} }
      end

    elsif params['claim_requests'].present?
      if params['claim_requests']['email'].present?
        @email = params['claim_requests']['email']
        @resources = @resources.email_search(@email.downcase)
      end
    end
    @resources = klass.where(granted: params[:granted]) if params[:granted].present?
    @resources = @resources.order(created_at: :desc).page(params[:page])
  end


  def update
    # To get around some strange behaviour of accepts nested_attributes, just seperate out the user params to update
    # the relevent user fields.
    @user = User.find(resource_params["user_id"])
    @saved = User.transaction do
      begin
        @resource.update_attributes!(resource_params.except(:user))
        @user.update_attributes!(resource_params["user"])
      rescue
        false
      end
    end
    if @saved
      if @resource.granted?
        RoleAssigner.new(@resource.user, "moderator", @resource.claimable).assign
      else
        current_user.remove_role(:moderator, @resource.claimable)
      end
      redirect_to index_path, notice: "Updated"
    else
      render :edit
    end
  end
end

app/controllers/claim_requests_controller.rb
class ClaimRequestsController < ApplicationController
  before_action :check_if_logged_in, only: [:create]
  before_action :find_resource
  layout 'design'
  add_breadcrumb 'Claim Request'

  def new
    set_meta_tags noindex: true
    if @location
      @claim_request = @location.claim_requests.new
      @claim_request.user = current_user
    else
      flash[:error] = "Not found requested #{params[:location_id]}."
      redirect_to root_url
    end
  end

  def create
    set_meta_tags noindex: true
    if @location.present?
      @claim_request = @location.claim_requests.new(claim_request_params)
    else
      @claim_request = ClaimRequest.new(claim_request_params)
    end
    @claim_request.user_id = current_user.id
    @claim_request.created_by = current_user.id
    if @claim_request.save
      ClaimRequestMailer.notify(@claim_request).deliver_now
      if @location.present?
        if @location.class.to_s == 'MedicalStudent'
          redirect_to medical_student_path(@location), notice: t("claim_request.saved")
        elsif @location.doctor?
          redirect_to helpers.doctor_path(@location), notice: t("claim_request.saved")
        elsif @location.hospital?
          redirect_to helpers.location_path(@location), notice: t("claim_request.saved")
        else
          redirect_to @location, notice: t("claim_request.saved")
        end
      else
        # Ideally, this should be a render instead of a redirect, but because of layout issues, using render attempts to
        # render the provider_info page in the application layout instead of the design layout. Rather than reproduce all
        # of the styling in application (and potentially breaking something), just redirect to the action.
        redirect_to controller: "static_pages", action: "manage"
      end
    else
      # if the claim request is being made on a location, reload the relevent location claim request new form.
      if @location.present?
        render :new
      # Otherwise it is being made from the generic location claim form on providers_info.
      else
        # Ideally, this should be a render instead of a redirect, but because of layout issues, using render attempts to
        # render the provider_info page in the application layout instead of the design layout. Rather than reproduce all
        # of the styling in application (and potentially breaking something), just redirect to the action.
        redirect_to controller: "static_pages", action: "manage"
      end
    end

  end

  private

  def check_if_logged_in
    if current_user.nil?
      if request.params["claim_request"]["user"].present?
        session[:email] = request.params["claim_request"]["user"]["email"]
      end
      if request.params.slice(:doctor_id).present?
        session[:user_return_to] = create_doctor_claim_request_url(request.params.slice(:claim_request, :doctor_id))
      else
        session[:user_return_to] = create_claim_request_url(request.params.slice(:claim_request, :location_id))
      end
      redirect_to new_user_registration_url(provider: true, hide_claim_request_form: true)
    end
  end

  def claim_request_params
    params.require(:claim_request).permit(:position, :phone, :description, :email, :country_code, :name, :created_by)
  end

  def find_resource
    if params[:location_id].present?
      @location = Location.find(params[:location_id])
    elsif params[:claim_request].present? and params[:claim_request][:location_id].present?
      @location = Location.find(params[:claim_request][:location_id])
    end
  end
end

app/views/admin/claim_requests/_form.html.slim
- if @resource.new_record?
  - claimable_ids = []
  - user_ids = [[@current_user.email, @current_user.id]]
- else
  - claimable_ids = [[@resource.claimable&.name, @resource.claimable_id]]
  - user_ids = [[@resource.user.email, @resource.user_id]]

= simple_form_for [:admin, @resource ], url: @form_url do |f|
  - if @resource.new_record?
    = f.input :claimable_type, as: :select, collection: ["Doctor", "Location", 'MedicalStudent'], input_html: {onchange: "update_claimable_id_ddl();"}, required: true
    = f.input :claimable_id, as: :select, collection: claimable_ids
  - else
    = f.input :claimable_type, as: :select, collection: ["Doctor", "Location", 'MedicalStudent'], input_html: {disabled: true}
    = f.input :claimable_id, as: :select, collection: claimable_ids, input_html: {disabled: true}
  = f.input :user_id, as: :select, collection: user_ids, label: 'Claim By', input_html: {onchange: "update_user_id_ddl();"}, include_blank: 'Select Other User', required: true
  = f.input :country_code, as: :select, collection: country_alpha3_collection, label: "Country", selected: @resource&.country_code
  = f.input :phone
  = f.input :description
  = f.input :position
  = f.input :granted
  = f.hidden_field :created_by, value: @current_user.id
  = f.fields_for @resource.user do |u|
    = u.input :marked_as_provider
  = f.button :submit

javascript:

  function update_user_id_ddl(){
    $('#claim_request_user_id').select2({
        allowClear: true,
        minimumInputLength: 5,
        maximumResultsForSearch: 20,
        ajax: {
          url: '/admin/claim_requests/',
          dataType: 'json',
          delay: 250,
          async: false,
          data: function (params) {
            var query = {
              user_name: params['term'],
              page: params.page || 1
            }
            return query;
          },
          processResults: function (data, params) {
          return {
            results: data,
            pagination: {
              more: true
            }
          };
         },
         cache: true
        }
      })
  }

  function update_claimable_id_ddl(){
    type = $('#claim_request_claimable_type').val();
    if (type == ''){
      $('#claim_request_claimable_id').prop("disabled", true);
    }
    else{
      $('#claim_request_claimable_id').prop("disabled", false);
      $('#claim_request_claimable_id').select2({
        allowClear: true,
        minimumInputLength: 5,
        maximumResultsForSearch: 20,
        ajax: {
          url: '/admin/claim_requests/',
          dataType: 'json',
          delay: 250,
          async: false,
          data: function (params) {
            var query = {
              claimable: type,
              claimable_term: params['term'],
              page: params.page || 1
            }
            return query;
          },
          processResults: function (data, params) {
          return {
            results: data,
            pagination: {
              more: true
            }
          };
         },
         cache: true
        }
      })
    }
  }

app/views/admin/claim_requests/_list.html.slim
tr
  td=list.granted?
  td=link_to list.user.username, edit_admin_user_path(list.user_id), title: list.user.username if list.user.present?
  td=list.user.email if list.user.present?
  td= list.phone.present? ? list.phone : (list.user.phone_number if list.user.present?)
  td
    - if list.claimable.present?
  	 =link_to list.claimable.name, list.claimable, title: list.claimable.name
  td
    =list.country_code
  td=link_to "Edit", [:edit, :admin, list], class: 'button tiny', title: 'Edit'
  td=link_to "Delete", [:admin, list], method: :delete, class: 'button tiny alert', title: 'Delete'

app/views/admin/claim_requests/index.html.slim
br
h1
  | Claim Requests
hr
.row
  .columns.medium-4
    .button-group
      =link_to "All", [:admin, :claim_requests], class: "button", title: 'All'
      =link_to "All Granted", "?granted=true", class: "button", title: 'All Granted'
      =link_to "All Not Granted", "?granted=false", class: "button", title: 'All Not Granted'
      =link_to "Add", [:new, :admin, 'claim_request' ], class: "button", title: 'Add Claim'
  =simple_form_for 'claim_requests', url: admin_claim_requests_path, class: "search-form", method: :get do |f|
    .columns.medium-6
      =f.input :email, label: false, placeholder: 'Email', input_html: {value: @email}
    / .columns.medium-3
    /   =f.input :location, label: false, placeholder: 'Location/Doctor', input_html: {value: @location}
    .columns.medium-1
      =f.button :button, "Search"
    .columns.medium-1
      =link_to "Clear", admin_claim_requests_path, title: 'Clear Search'
hr
table data-nosort=""
  thead
    tr
      th Granted?
      th User
      th Email
      th Phone
      th Location/Doctor
      th Country
      th
      th
  tbody
    = render partial: "list", collection: @resources

- if @resources.present?
  .text-center
    = paginate(@resources)

app/views/admin/claim_requests/update_ddl.js.erb
$('#claim_request_claimable_id').empty();
$('#claim_request_claimable_id').append( $('<option>Select a <%= @type %> </option>'));
<% @resource_data.each do |resource| %>
  $('#claim_request_claimable_id').append($('<option value="<%= resource.first %>"><%= resource.last %></option>'));
<% end %>
$('.select2').select2();