config/routes.rb
    end
  end

  get 'sitemap', to: 'sitemaps#index', defaults: {format: 'html'}

  post "interested_provider_contact" => "users#provider_email_request", as: :interested_provider_contact
  post "create_subscription_only_user" => "users#create_subscription_only"
  get "create_claim_request", to: "claim_requests#create", as: :create_claim_request
  get "create_doctor_claim_request", to: "doctor_claim_requests#create", as: :create_doctor_claim_request
  get 'contributors' => 'static_pages#editorial_board', as: :editorial_board
  get "privacy-policy" => "static_pages#privacy_policy"
  get "terms" => "static_pages#terms"
  get "copyright" => "static_pages#copyright"
  get "faqs" => "static_pages#faqs"
  get "press" => "static_pages#press"
  get "careers" => "static_pages#careers"
  get "about" => "static_pages#about"
  get "claims/(:id)" => "static_pages#manage", as: :manage
  get "users/(:id)" => "static_pages#users_info", as: :users_info
  get '/home/(:set_locale)' => "home#index"
  get "india" => "home#india"
  get "calculators" => "static_pages#calculators"
  get "bmi_calculator" => "static_pages#bmi_calculator"
  get "waist_hip_calculator" => "static_pages#waist_hip_calculator"
  get "bmr_calculator" => "static_pages#bmr_calculator"
  get "calorie_calculator" => "static_pages#calorie_calculator"
  post "email_my_calculator_results" => "users#mail_calculator_results"

  # Health Guides
  get "health-guide" => "health_guides#index"
  get "health-guides" => "static_pages#health_guide"
  scope 'health-guide', as: :health_guide do
    get ":co" => "health_guides#show", as: :co
  end

  # Faq / Forum
  get "/forum" => "faqs#index"
  resources :faqs, only: [ :create, :update ] do
    resources :faq_answers, only: :create
  end

  get "/blog/tag/:tag" => "blogs#index", as: :blogs_tag
  resources :blogs, path: "blog", only: [ :index, :show] do
    member do
      patch 'share_blog/:social_platform', action: 'share_blog', defaults: {format: 'json'}
    end
  end
  resources :contacts, only: [:new, :create]
  resources :advertising_requests, only: [:new, :create]

  get "locations/compare" => "compare#index", as: :search_hospital_compare
  get "locations/compare" => "compare#index", as: :search_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_travel_health_insurance_compare
  get "locations/compare" => "compare#index", as: :search_healthcare_facilities_compare
  get "doctors/compare" => "doctor_compare#index", as: :search_doctor_compare

  # Search Prep
  get "home-prep-hospitals" => "home#prep_hospitals", as: :prep_hospital_search
  get "home-prep-health-insurance" => "home#prep_health_insurance", as: :prep_health_insurance_search

  post "agree_to_gdpr" => "home#agree_to_gdpr"
  # Search
  get "hospitals" => "searches#show", as: :search_hospitals
  get "doctors" => "doctor_search#show", as: :search_doctors
  get "typeahead" => "doctor_search#typeahead_search", as: :search_typeahead

  get "practices" => "practice#show", as: :search_practices
  get "health-insurance/(:set_locale)" => "health_insurance#show", as: :search_health_insurances
  get "travel-health-insurance/(:set_locale)" => "travel_health_insurance#show", as: :search_travel_health_insurances
  get "healthcare-facilities/(:set_locale)" => "healthcare_facilities#show", as: :search_healthcare_facilities

  get "best-hospital-ratings/:set_locale/(:state)/(:city)" => "searches#best_hospitals", as: :search_best_hospitals
  get "best_hospitals/:set_locale/(:state)/(:city)" => "searches#best_hospitals"
  get '/best-hospital-ratings/:country/:state/:city/:id/reviews', controller: :locations, action: :show
  get '/best-hospital-ratings/:country/:state/:city/:id', controller: :locations, action: :show
  get '/practices/:top_speciality/:country/:state/:city/:id', controller: :locations, action: :practice

  get '/health-insurance/:country/:id', controller: :locations, action: :health_insurance
  get '/travel-health-insurance/:country/:id', controller: :locations, action: :travel_health_insurance

  get "best_doctors/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors"
  get "practices/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_practices

  get "best-doctor-ratings/:speciality/:set_locale/(:state)/(:city)" => "doctor_search#best_doctors", as: :search_best_doctors
  get '/best-doctor-ratings/:top_speciality/:country/:state/:city/:id', controller: :doctors, action: :show

  post "/blog/image-upload" => 'admin/blogs#image_upload'

  resources :ratings, only: [] do
    resources :comments
  end

  resources :doctor_reviews, only: [] do
    resources :comments
  end
  
  resources :practice_reviews, only: [] do
    resources :comments
  end

  resources :questions, :only => [] do
    resources :answers, only: [:new, :create]
  end

#trailing out health rating
  resources :hs


     get "patient-experience-awards" => "awards#index", as: :awards
     match 'excellent-patient-experience-awards-doctors' => 'awards#gold_doctors', as: :gold_doctors_awards, via: [:get, :post]
     match 'excellent-patient-experience-awards-hospitals' => 'awards#gold_hospitals', as: :gold_hospitals_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-doctors' => 'awards#diamond_doctors', as: :diamond_doctors_awards, via: [:get, :post]
     match 'exceptional-patient-experience-awards-hospitals' => 'awards#diamond_hospitals', as: :diamond_hospitals_awards, via: [:get, :post]

  # API
  namespace :api do
    get "votes/:voteable_type/:voteable_id/:status" => "votes#create"
    resources :locations, only: :index
    # resources :doctor_organizations, only: :index
    resources :doctors, only: :index
    resources :reset_passwords, only: [:index, :create]
    resources :register_user, defaults: {format: 'json'} do
      collection do
       post 'create_user'
       post 'login'
       delete 'logout'
       get "/doctor_show" => "/api/doctors#doctor_show"
       get "/hospital_show" => "/api/doctors#hospital_show"
       get "/doctor_review" => "/api/doctors#doctor_review"
       get "/hospital_review" => "/api/doctors#hospital_review"
       post "/update_profile" => "/api/register_user#update_profile"
       get "/healthinsurance_show" => "/api/doctors#healthinsurance_show"
       get "/healthinsurance_review" => "/api/doctors#healthinsurance_review"
       post "/create_review" => "/api/doctors#create_review"
       post "/create_hospital_review" => "/api/doctors#create_hospital_review"
       post "/create_insurance_review" => "/api/doctors#create_insurance_review"
       get "/mailchimp" => "/api/mailchimp#mailchimp"
       post "/create_appointment" => "/api/appointment#create_appointment"
       get "/appointment_show" => "/api/appointment#appointment_show"
       get "/user_point_review" => "/api/register_user#user_point_review"
       get "/search_doctor" => "/api/search#search_doctor"
       get "/search_hospital" => "/api/locations#search_hospital"
       get "/search_health_insurance" => "/api/health_insurance#search_health_insurance"
      end
    end
  end

  # manager
  namespace :manage do
    resources :locations
    resources :doctors do
      get "show1"
      get "reply_review/:rating_id" => "doctors#reply_review"
      post "save_review"
    end
  end

  # Admin
  namespace :admin do
    root to: "dashboard#index"
    resources :advertisements do
      member do
        match 'resource_mapping' => "advertisements#resource_mapping", via: [:get, :patch]
      end
    end
    resources :board_certifications
    resources :doctor_hospitals do
      collection do
        post "import"
      end
    end
    resources :languages
    resources :medical_students
    resources :events
    resources :event_members
    resources :editorial_members
    resources :appointments
    resources :location_types
    resources :locations do
      member do
        post 'analytics_report' => 'locations#analytics_report'
      end
    end
    resources :conditions
    resources :doctors do
      member do
        post 'analytics_report' => 'doctors#analytics_report'
      end
    end
    resources :users
    resources :claim_requests
    resources :questions
    resources :ratings
    resources :doctor_reviews
    resources :practice_reviews
    resources :speciality_merges
    resources :doctor_reports, only: :index
    get "practices" => "doctors#practices"
    get "doctor_reports/doctor_uploads" => "doctor_reports#doctor_uploads"
    resources :practice_specialities do 
      member do
        get 'faqs' => 'practice_specialities#faqs'
      end
    end
    resources :practice_specialities_faqs
    resources :procedures
    resources :blogs
    resources :tags
    namespace :import do
      resources :locations, only: [:new, :create]
      resources :doctors, only: [:new, :create]
    end
    resources :promotions do
      resources :promotion_winners
    end
  end

  resources :doctors, only: :show do
    resources :questions, only: [:new, :create]
    resources :ratings, only: [:new], controller: "doctor_reviews"
    resources :doctor_reviews, only: [:create, :index]
    resources :claim_requests, only: [:new, :create], controller: "doctor_claim_requests"
    resources :appointments, provider_type: 'doctor'
    member do
      post 'save_favorite' => "favorites#create"
      post 'remove_favorite' => "favorites#destroy"
    end
  end

  resources :appointments

  resources :locations, only: [:show], path: "" do
    resources :ratings, only: [:new, :create, :index]
    resources :practice_reviews, only: [:new, :create, :index]
    resources :questions, only: [:new, :create]
    resources :claim_requests, only: [:new, :create]
  end

  resources :claim_requests, only: [:new, :create]

  resources :locations, only: :update do
    member do
      post 'save_favorite' => "favorites#create"
      post 'remove_favorite' => "favorites#destroy"
    end
  end

app/models/award.rb
class Award < ApplicationRecord
	belongs_to :doctor, class_name: "Doctor", foreign_key: :location_id
	belongs_to :location, class_name: "Location", foreign_key: :location_id
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  layout 'design'

  def index
    add_breadcrumb "Awards", :awards
    set_meta_tags title: "Patient Experience Awards"
    set_meta_tags description: "Patient Experience Awards"
  end

  def gold_doctors
    add_breadcrumb "Gold Doctors", :gold_doctors_awards
    set_meta_tags title: "Excellent Patient Experience Awards Doctors"
    set_meta_tags description: "Excellent Patient Experience Awards Doctors"
    country = params[:location].present? ? params[:location] : "USA"
    @doctors = Doctor.joins(:awards).where("awards.location_type =? AND awards.year =? AND awards.award_type =? AND doctors.country =?", 'Doctor', Date.today.year, 'gold', country).order("doctors.ratings_count desc").limit(50)
  end

  def diamond_doctors
    add_breadcrumb "Diamond Doctors", :diamond_doctors_awards
    set_meta_tags title: "Exceptional Patient Experience Awards Doctors"
    set_meta_tags description: "Exceptional Patient Experience Awards Doctors"
    country = params[:location].present? ? params[:location] : "USA"
    @doctors = Doctor.joins(:awards).where("awards.location_type =? AND awards.year =? AND awards.award_type =? AND doctors.country =?", 'Doctor', Date.today.year, 'diamond', country).order("doctors.ratings_count desc").limit(50)
  end

  def gold_hospitals
    add_breadcrumb "Gold Hospitals", :gold_hospitals_awards
    set_meta_tags title: "Excellent Patient Experience Awards Hospitals"
    set_meta_tags description: "Excellent Patient Experience Awards Hospitals"
    country = params[:location].present? ? params[:location] : "USA"
    @hospitals = Location.joins(:awards).where("awards.location_type =? AND awards.year =? AND awards.award_type =? AND locations.country =?", 'Hospital', Date.today.year, 'gold', country).order("locations.ratings_count desc").limit(50)
  end

  def diamond_hospitals
    add_breadcrumb "Diamond Doctors", :diamond_hospitals_awards
    set_meta_tags title: "Exceptional Patient Experience Awards Hospitals"
    set_meta_tags description: "Exceptional Patient Experience Awards Hospitals"
    country = params[:location].present? ? params[:location] : "USA"
    @hospitals = Location.joins(:awards).where("awards.location_type =? AND awards.year =? AND awards.award_type =? AND locations.country =?", 'Hospital', Date.today.year, 'diamond', country).order("locations.ratings_count desc").limit(50)
  end
end

app/views/awards/_doctors_listing.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover"> 
          <thead class=" revise-doctor-frame-top">
            <tr>
              <th width="22%;">Doctor's Name</th>
              <th width="13%;">Speciality</th>
              <th width="10%;">Reviews</th>
              <th width="25%;">Average User Rating</th>
              <th width="30%;">Address</th>
            </tr>
          </thead>
          <tbody>
            <% @doctors.each do |doctor| %>
              <% doctor = doctor.decorate %>
              <tr>
                <td><%= link_to doctor.name, doctor_path(doctor) %></td>
                <td><%= doctor.primary_speciality %></td>
                <td><%= doctor.ratings_count %></td>
                <td><%= doctor.stars %>
                  (<%= doctor.overall %>/5)
                </td>
                <td class='not-telephone'><%= doctor.org_name %>
                  <%= prop :address, doctor.address %><br>
                  <% if doctor.address2.present? %>
                    <%= doctor.address2 %>
                    <br>
                  <% end %>
                  <%= doctor.city_state_zip %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!--end of .table-responsive-->
    </div>
  </div>
</div>

app/views/awards/_filter.html.erb
<% country = params[:location].blank? ? "USA's" : "#{params[:location]}'s" %>
<div class="row filter">
  <div class="col-md-12">
    <div class="award-top-heading">
      <%= country %> Best <%= loc %> for <%= Date.today.year %>
    </div>
  </div>
</div>

<div class="container filter">
  <div class="row"> 
    <div class="col-md-12">
      <div class="hospital-reviews-result">
        <div class="row">
          <div class="col-md-6"></div>
          <div class="col-md-6">
            <div class="soft-buyreviews-frame pull-right">
              <span>
                <%= form_tag path_name do %>
                  Filter By Country: &nbsp;<%= select_tag "location", options_for_select([ "USA", "India" ], selected: params[:location].present? ? params[:location] : "USA"), {class: "form-control", onchange: "$(this).parent('form').submit();"} %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
	  </div>
	</div>
</div>
			
<div class="clear"></div>

app/views/awards/_hospitals_listing.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="table-responsive">
        <table class="table table-hover"> 
          <thead class="revise-doctor-frame-top">
            <tr>
              <th width="25%;">Hospital's Name</th>
<!--               <th>Speciality</th>
 -->              <th width="10%;">Reviews</th>
              <th width="25%;">Average User Rating</th>
              <th width="40%;">Address</th>
            </tr>
          </thead>
          <tbody>
                 <% @hospitals.each do |hospital| %>
                        <% hospital = hospital.decorate %>
                        <tr>
                             <td><%= link_to hospital.name, location_path(hospital) %></td>
<!--                              <td><%#= hospital.primary_speciality %></td>
 -->                             <td><%= hospital.ratings_count %></td>
                             <td><%= hospital.stars %>
                                  (<%= hospital.overall %>/5)
                              </td>
                              <td class='not-telephone'>
                                  <%= prop :address, hospital.address %><br>
                                   <% if hospital.address2.present? %>
                                  <%= hospital.address2 %>
                                  <br>
                                <% end %>
                                <%= hospital.city_state_zip %>
                              </td>
                        </tr>
                  <% end %>
          </tbody>
          
        </table>
      </div><!--end of .table-responsive-->
    </div>
  </div>
</div>

app/views/awards/diamond_doctors.html.erb
<section class="sign-up-banner">
  <div class="sign-up-banner-inner-page">
    <a href="<%= awards_path %>" title='healthsoul award'> <%= image_tag "healthsoul-award-banner.jpg", alt: "healthsoul award", title: "healthsoul award" %>
    </a>
  </div>
</section>

<div class="clear"></div>
<br/>
<section>
      <%= render partial: "awards/filter", locals: {path_name: diamond_doctors_awards_path, loc: 'Doctors'} %>
      <%= render partial: "awards/doctors_listing" %>
      <div class="container">  
            <div class="row">      
                 <div class="Previous-next-h-review-bottom-frame">
                      <div class="row">
                        <div class="col-md-10">
                        
                        </div>
                      </div>
                  </div>        
            </div>
      </div>
</section>
<div class="clear"></div>

app/views/awards/diamond_hospitals.html.erb
<section class="sign-up-banner">
  <div class="sign-up-banner-inner-page">
    <a href="<%= awards_path %>" title="healthsoul award">
       <%= image_tag "healthsoul-award-banner.jpg", alt: "healthsoul award", title: "healthsoul award" %>
    </a>
  </div>
</section>

<div class="clear"></div>
<br/>
<section>
  <%= render partial: "awards/filter", locals: {path_name: diamond_hospitals_awards_path, loc: 'Hospitals'} %>
  <%= render partial: "awards/hospitals_listing" %>
</section>
<div class="clear"></div>

app/views/awards/gold_doctors.html.erb
<section class="sign-up-banner">
  <div class="sign-up-banner-inner-page">
    <a href="<%= awards_path %>" title="healthsoul award">
       <%= image_tag "healthsoul-award-banner.jpg", alt: "healthsoul award", title: "healthsoul award" %>
    </a>
  </div>
</section>

<div class="clear"></div>
<br/>
<section>
  <%= render partial: "awards/filter", locals: {path_name: gold_doctors_awards_path, loc: 'Doctors'} %>
  <%= render partial: "awards/doctors_listing" %>
</section>
<div class="clear"></div>

app/views/awards/gold_hospitals.html.erb
<section class="sign-up-banner">
  <div class="sign-up-banner-inner-page">
    <a href="<%= awards_path %>" title="healthsoul award">
       <%= image_tag "healthsoul-award-banner.jpg", alt: "healthsoul award", title: "healthsoul award" %>
    </a>
  </div>
</section>

<div class="clear"></div>
<br/>
<section>
  <%= render partial: "awards/filter", locals: {path_name: gold_hospitals_awards_path, loc: 'Hospitals'} %>
  <%= render partial: "awards/hospitals_listing" %>    
</section>
<div class="clear"></div>

app/views/awards/index.html.erb
<section class="sign-up-banner">
  <div class="sign-up-banner-inner-page">
    <a href="<%= awards_path %>" title="healthsoul award">
      <%= image_tag "healthsoul-award-banner.jpg", alt: "healthsoul award", title: "healthsoul award" %>
    </a>
  </div>
</section>

<div class="clear"></div>
<!--award-para-section start-->

<section class="award-para-section">
  <div class="container">
  	<div class="row">
  		<div class="col-md-12">
  			<div class="award-top-heading">
  			  Guiding Principles for Award Distribution
  			</div>
  		</div>
  	</div>
  	
  	<div class="row">
  		<div class="col-md-12">
  			<div class="award-top-paragraph">
  			  <p>
    			 These awards are given to physicians, physician practices, hospitals, health insurance and travel
    health insurance in recognition of outstanding patient and consumer satisfaction. These are
    awarded based on the average score in a year given by patients based on their healthcare
    experience. The healthcare entity must have atleast 5 reviews to gain an award.
  			  </p>
  			</div>
  		</div>
  	</div>
  	
  </div>	
</section>

<section class="award-para-section">
  <div class="container">
  	<div class="row">
  		<div class="col-sm-2 col-sm-offset-0 col-xs-6 col-xs-offset-3">
  			<div class="award-distribution-img-main">
  					<%= image_tag "diamond.jpg" %>
  				</div>
  		</div>
  		
    	<div class="col-sm-10 col-xs-12">
    		<div class="award-distribution-guiding">
    		<p class="award-distribution-heading">
    			Gold Award indicates Exceptional Patient Experience
    		</p>	
    		<p>
    			This award is for healthcare professionals who have received 5-star rating from their patients during a particular year.
    		</p>	
    		</div>
    	</div>
  	</div>
  	
  	<div class="row">
  		<div class="col-sm-2 col-sm-offset-0 col-xs-6 col-xs-offset-3">
  			<div class="award-distribution-img-main">
  					<%= image_tag "gold.jpg" %>
  				</div>
  		</div>
  		
    	<div class="col-sm-10 col-xs-12">
    		<div class="award-distribution-guiding">
      		<p class="award-distribution-heading">
      			Silver Award indicates Excellent Patient Experience
      		</p>	
      		<p>
      			This award is for healthcare professionals who have received more than 4-star rating but less than 5-star rating from their patients during a particular year.
      		</p>	
    		</div>
    	</div>
  	</div>
  	
  	<div class="row">
  		<div class="col-sm-2 col-sm-offset-0 col-xs-6 col-xs-offset-3">
  			<div class="award-distribution-img-main">
  				<%= image_tag "silver.jpg" %>
  			</div>
  		</div>
  		
  	  <div class="col-sm-10 col-xs-12">
  		  <div class="award-distribution-guiding">
  		    <p class="award-distribution-heading">
  			    Bronze Award indicates Good Patient Experience
      		</p>	
      		<p>
      			This award is for healthcare professionals who have received more than 3-star rating but less than 4-star rating from their patients during a particular year.
      		</p>	
  		  </div>
  	  </div> 		
  	</div>  	
  </div>
</section>

<section class="award-para-section">
<div class="container">

	<div class="row">
		<div class="col-md-12">
			<div class="award-top-heading">
			  Patients Experience and Satisfaction Awards - For Doctors
			</div>
		</div>
	</div>
	
</div>

<div class="container">	
<div class="award-healthsoul-section">	

	<div class="row">
		<div class="col-md-6">
		
			<div class="healthsoul-award-box-main-left">
				<div class="healthsoul-award-img-main">
					<%= image_tag "diamond.jpg" %>
				</div>
				<div class="healthsoul-award-txt-main">
					<a href="<%= diamond_doctors_awards_path %>">View Recipients</a>
				</div>
			</div>
		
		</div>
		
		<div class="col-md-6">
		
			<div class="healthsoul-award-box-main">
				<div class="healthsoul-award-img-main">
					<%= image_tag "gold.jpg" %>
				</div>
				<div class="healthsoul-award-txt-main">
					<a href="<%= gold_doctors_awards_path %>">View Recipients</a>
				</div>
			</div>
		
		</div>
	</div>
	
</div>
</div>


<div class="container">

	<div class="row">
		<div class="col-md-12">
			<div class="award-top-heading">
			 Patients Experience and Satisfaction Awards - For Hospitals
			</div>
		</div>
	</div>
	
</div>

<div class="container">	
<div class="award-healthsoul-section">	

	<div class="row">
		<div class="col-md-6">
		
			<div class="healthsoul-award-box-main-left">
				<div class="healthsoul-award-img-main">
					<%= image_tag "diamond.jpg" %>
				</div>
				<div class="healthsoul-award-txt-main">
					<a href="<%= diamond_hospitals_awards_path %>">View Recipients</a>
				</div>
			</div>
		
		</div>
		
		<div class="col-md-6">
		
			<div class="healthsoul-award-box-main">
				<div class="healthsoul-award-img-main">
					<%= image_tag "gold.jpg" %>
				</div>
				<div class="healthsoul-award-txt-main">
					<a href="<%= gold_hospitals_awards_path %>">View Recipients</a>
				</div>
			</div>
		
		</div>
	</div>
	
</div>
</div>

</section>	

<!--award-para-section end-->